/**
 * Default banned vocabulary, phrases, and openers.
 *
 * Sources:
 * - Carnegie Mellon 2025 study on LLM lexical fingerprints
 * - Wikipedia: Signs of AI writing
 * - Buffer 52M-post analysis (2025)
 * - Empirical observation of Claude Opus 4.x, GPT-5.x, Gemini 3 output
 *
 * Edit your local config (.antislop.yml) to add, remove, or override.
 */

export const DEFAULT_BANNED_VOCAB: string[] = [
  // Verb-form slop
  "delve",
  "delves",
  "delving",
  "leverage",
  "leverages",
  "leveraged",
  "leveraging",
  "harness",
  "harnesses",
  "harnessed",
  "harnessing",
  "unlock",
  "unlocks",
  "unlocking",
  "unleash",
  "unleashed",
  "showcase",
  "showcases",
  "showcasing",
  "underscore",
  "underscores",
  "underscored",
  "underscoring",
  "spearhead",
  "spearheading",
  "navigating",
  "highlighting",
  "emphasizing",
  "enhancing",
  "fostering",
  "foster",
  "garner",
  "garners",
  "garnered",
  "bolster",
  "bolsters",
  "bolstered",
  "bolstering",
  "facilitate",
  "facilitates",
  "facilitated",
  "encompass",
  "encompasses",
  "encompassing",
  "captivate",
  "captivating",
  "elevate",
  "elevates",
  "elevated",
  "streamline",
  "streamlines",
  "streamlined",
  "supercharge",
  "supercharged",
  "empower",
  "empowers",
  "empowered",
  "empowering",
  "revolutionize",
  "revolutionizes",
  "revolutionized",
  "revolutionise",
  "revolutionised",
  "reimagine",
  "reimagines",
  "redefine",
  "redefines",
  "democratize",
  "democratizes",
  "accelerate",
  "accelerates",
  "transform",
  "transformative",
  "synergize",
  "synergy",
  "synergies",
  "optimize",
  "optimizes",
  "optimized",
  "align",
  "aligned",
  "aligning",
  "utilize",
  "utilizes",
  "utilized",
  "utilizing",
  "commence",
  "commences",
  "commenced",
  "endeavor",
  "endeavors",
  "endeavour",
  "endeavours",

  // Noun-form slop
  "tapestry",
  "landscape",
  "realm",
  "paradigm",
  "interplay",
  "testament",
  "intricacies",
  "intricacy",
  "synergy",
  "thought-leader",

  // Adjective slop
  "intricate",
  "vibrant",
  "pivotal",
  "crucial",
  "meticulous",
  "meticulously",
  "multifaceted",
  "nuanced",
  "paramount",
  "groundbreaking",
  "cutting-edge",
  "game-changing",
  "transformative",
  "seamless",
  "seamlessly",
  "robust",
  "comprehensive",
  "unprecedented",
  "remarkable",
  "stunning",
  "profound",
  "epic",
  "vibrant",
  "innovative",
  "scalable",
  "frictionless",
  "adaptive",
  "effortless",
  "insightful",
  "proactive",
  "visionary",
  "disruptive",
  "intuitive",
  "leading-edge",
  "state-of-the-art",
  "dynamic",
  "immersive",
  "predictive",
  "data-driven",
  "mission-critical",
  "future-proof",
  "paradigm-shifting",
  "plug-and-play",
  "turnkey",
  "trailblazing",
  "pioneering",
  "valuable",
  "commendable",
  "holistic",

  // Filler nouns
  "aforementioned",

  // 2026-era buzz
  "agentic",
  "ai-native",
  "ai-first",
  "ai-augmented",
  "10x",
  "north-star",
  "north star",
  "table stakes",
  "ground truth",
  "first-principles"
];

export const DEFAULT_BANNED_PHRASES: string[] = [
  // The big rhythm tells
  "let's dive in",
  "let's dive deeper",
  "let's delve into",
  "let's explore",
  "let's unpack",
  "in today's",
  "in the realm of",
  "at its core",
  "when it comes to",
  "a testament to",
  "this is where",
  "from x to y",
  "at the end of the day",
  "the bottom line is",
  "here's the thing",
  "here's the deal",
  "without further ado",
  "in a nutshell",
  "buckle up",
  "take it to the next level",
  "unlock the power of",
  "bridge the gap",
  "move the needle",
  "in conclusion",
  "i hope this helps",
  "i hope this email finds you well",
  "i hope this finds you well",
  "as per my last email",
  "please don't hesitate to reach out",
  "feel free to reach out",
  "to put this in perspective",
  "what makes this particularly interesting is",
  "the implications here are",
  "in other words",
  "it goes without saying",
  "here's the part nobody's talking about",
  "what nobody tells you",
  "most people don't realize",
  "let that sink in",
  "read that again",
  "this changes everything",
  "are you paying attention",
  "you're not ready for this",
  "it's worth noting that",
  "it's important to note that",
  "it is worth noting that",
  "it is important to note that",
  "moving forward",
  "touch base",
  "circle back",
  "rest assured",
  "in order to",

  // The collaboration leak
  "i'd be happy to",
  "happy to help",
  "great question",
  "that's a great point",

  // 2026 verbal tics
  "worth flagging",
  "worth noting",
  "quick heads up",
  "quick caveat",
  "for what it's worth",
  "real talk",
  "long story short",
  "the ask",
  "skin in the game",
  "ship it",
  "lock in",

  // Banned compound openers
  "in today's fast-paced",
  "in today's digital",
  "in the world of",

  // Vendor-marketing tone catch-alls
  "challenges and future prospects",
  "in this article, i will",
  "in this section, we will"
];

export const DEFAULT_BANNED_OPENERS: string[] = [
  "certainly",
  "absolutely",
  "sure",
  "great question",
  "that's a great point",
  "as an ai",
  "as a language model",
  "however, it's important",
  "moreover",
  "furthermore",
  "additionally",
  "interestingly",
  "notably",
  "importantly",
  "indeed"
];
